{% set name = "pyslet" %}
{% set version = "0.7.20170805" %}
{% set sha256 = "4f6cce9f60f9dc2543deee311da8b3e678fde3260971f301f4da2d40a4a30a8f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/swl10/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1003
  script: {{ PYTHON }} -m pip install . --no-deps -vv
 
requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - pyslet
    - pyslet.http
    - pyslet.odata2
    - pyslet.qtiv1
    - pyslet.qtiv2
    - pyslet.xml20081126

about:
  home: http://www.pyslet.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Pyslet: Python package for Standards in Learning, Education and Training'
  description: |
    Pyslet is a Python package for Standards in Learning Education and Training
    (LET). It implements a number of LET-specific standards, including IMS QTI,
    Content Packaging and Basic LTI. It also includes support for some general
    standards, including the data access standard OData (see
    http://www.odata.org).
  doc_url: https://pyslet.readthedocs.org
  dev_url: https://github.com/swl10/pyslet

extra:
  recipe-maintainers:
    - stuertz
