appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: M+Zljp9Gy/zLG8/yur/8FGeGxYXZ1+OOP2hlfeKVovXdVIKRstneKRU1xkmrBiapJX3NIiXkcTVCnS1gfmtWzvonu/4Ejkir5j6DbpLMKKiyyCYcYGFMrd1VnqaghSGC638veUUJrunA+kveno1z9skGalaKqbi7iAxAFu4T3CtRar6f2FMhb7RONvtl3hcVKT0QmQZbuIdsqF1wDT+tnilrp51ZzolcWRE+Voy9HaMd7SNZJLScmEjpXlDBFnsYPyZaEy4HxjS5K8IDZG6dSxpTEyUSMeviQhP2xAFVFegU78i/E+1EoIV6r3pwksHivAjHyJx6UHL/AWSgceEXAUJHoYhGUPjZxvEnL4lZO/MFpwkl2zhHdcsEAtUl+0ik8RykoYbSQnrAU5Omle1xREppk9jh/KNH8kYxe1F1y5duAXtzCjpauND30ksZprRsw7wFnIk53t9rLgW96kTSaQRvvgj3n5i+M7JaTFW6M4SGktGVq6oi2o24ioAGuQq4uJUli30kZScz7T0+fzhnJaxILjw2lgFJBf5gZ8qzptqhK1xurSHn7yGtjr4hCriu5nTpvPFtD9IJev64JQG/RWEmuv2SMc+SwDSeWBSDdFFhMOeCCJOZj8DQrxN648VKI1afAl1JeLn++1k2WJdI6eVNGgeS4eG4ey4Fd3T78KY=}
