travis:
  secure:
    BINSTAR_TOKEN: mV61GcZJPvTnIPEDdwiDpSQAfG80lByX4VohGC6E/ayLvB23Dg4VlNeGBfQj4BXGYa3LgQvQLZmeRvxdEeLG4cX3WhFBteTBg/kD2p+Of9zoq+N4Hi8wCOT6zkN8R72a5GYn3WnPGTDcVQune52ZQYvYYWJWyC5/YpEt5ZEz4x7Zl14bFYO5jgrRS2f7IPCG068LAzdI2/i0aI+wBoA4pkmOCpqs8HS/ZCSdh3FcJRcuBJurtlIa6JtLiuWP187+DUM5hGq7nJ8REWdmX5buwe7GDlkQKkUskex9dHDi7ZcYS8Q5L5VYT83ZIXqG6QAUfZjAnR1sUCm4tdKIomI/LO+W6J2aisqRT7fh+Ta89j0woIZn+Q2k0//mFpAu1M59h/BIUTi7OjJVgBfmCQb1/FzoLZIAgDM3bULe+3MKCLD54SXsRdw9XxRT/+TNj2uTVeMc/v88Lz3afP0Uwqdn9lbOpCELZlNK5qcECxqH6r8Vn/P4HcIs2yecyrGp1EzKt++QTvNHwQTz3feFYuZeMSoYQnIjZrJ4Kug6DW2A6Z+Az4Sm9fbUVcgQSxUqfNN7tbS6jmKZdE8bhxl7l2XOCWs5WpkJN3J6VV0tQFqBlwMwOofhmoEXYgTCv9h4klO95NC49lwcP1JAthz09UBo3dyQBb+SIzya4NAIaRWAf/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
